/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fff8f0",
        "on-tertiary-fixed-variant": "#444749",
        "surface-variant": "#ebe2cf",
        surface: "#fff8f0",
        "tertiary-fixed": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#edc200",
        "on-secondary-container": "#586377",
        "tertiary-fixed-dim": "#c4c7c9",
        "primary-fixed-dim": "#edc200",
        "on-surface-variant": "#4d4632",
        "on-primary-fixed-variant": "#564500",
        "on-primary": "#ffffff",
        "secondary-container": "#d5e0f8",
        "on-secondary-fixed": "#111c2d",
        "on-primary-fixed": "#231b00",
        tertiary: "#5c5f61",
        "inverse-on-surface": "#f9f0dd",
        "surface-tint": "#725c00",
        "on-primary-container": "#6f5a00",
        error: "#ba1a1a",
        "surface-container-highest": "#ebe2cf",
        "outline-variant": "#d1c6ab",
        primary: "#725c00",
        "surface-container": "#f6eddb",
        "on-surface": "#1f1b10",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-container": "#d4d6d8",
        "surface-container-high": "#f0e7d5",
        "on-tertiary-container": "#595d5f",
        "surface-dim": "#e2d9c7",
        "primary-fixed": "#ffe07f",
        "inverse-surface": "#353024",
        "on-tertiary-fixed": "#191c1e",
        "primary-container": "#ffd100",
        "secondary-fixed": "#d8e3fb",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#bcc7de",
        "on-background": "#1f1b10",
        "surface-container-low": "#fcf3e0",
        secondary: "#545f73",
        outline: "#7f765f",
        "on-error-container": "#93000a",
        "surface-bright": "#fff8f0",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
      },
    },
  },
  plugins: [],
};
