/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#f9bd22",
        "inverse-primary": "#bec6e0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#001a42",
        "on-background": "#191c1e",
        "surface-tint": "#565e74",
        outline: "#76777d",
        "tertiary-fixed": "#d8e2ff",
        "surface-dim": "#d8dadc",
        "on-primary-container": "#7c839b",
        "tertiary-fixed-dim": "#adc6ff",
        "on-secondary-fixed": "#261a00",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-container": "#6f5100",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "tertiary-container": "#001a42",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#004395",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffc329",
        "surface-container": "#eceef0",
        "on-secondary-fixed-variant": "#5c4300",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-container": "#3980f4",
        surface: "#f7f9fb",
        "primary-fixed": "#dae2fd",
        "inverse-surface": "#2d3133",
        primary: "#000000",
        "primary-container": "#131b2e",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#ffdf9f",
        "on-secondary": "#ffffff",
        secondary: "#795900",
        tertiary: "#000000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        xl: "32px",
        gutter: "20px",
        base: "4px",
        xs: "8px",
        lg: "24px",
        sm: "12px",
        md: "16px",
      },
      fontFamily: {
        "label-md": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "data-tabular": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "headline-xl": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "20px",
          { lineHeight: "28px", fontWeight: "700" },
        ],
        "data-tabular": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
