/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#111c2d",
        "on-tertiary-fixed-variant": "#92002a",
        "surface-dim": "#081425",
        "surface-tint": "#f1c100",
        "secondary-fixed-dim": "#7bd0ff",
        "on-tertiary-container": "#b60137",
        "surface-bright": "#2f3a4c",
        "inverse-surface": "#d8e3fb",
        "tertiary-fixed": "#ffdadb",
        surface: "#081425",
        error: "#ffb4ab",
        "primary-fixed": "#ffe08b",
        "surface-container-lowest": "#040e1f",
        "on-secondary-fixed-variant": "#004c69",
        primary: "#ffedc3",
        secondary: "#7bd0ff",
        "on-primary-container": "#6f5700",
        "on-primary-fixed-variant": "#584400",
        "inverse-primary": "#745b00",
        "on-surface": "#d8e3fb",
        tertiary: "#ffe9e9",
        "on-error": "#690005",
        "inverse-on-surface": "#263143",
        "on-secondary-container": "#00374d",
        "error-container": "#93000a",
        "surface-container": "#152031",
        "on-surface-variant": "#d2c5ab",
        "primary-container": "#ffcc00",
        background: "#081425",
        "surface-variant": "#2a3548",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#1f2a3c",
        "on-secondary": "#00354a",
        outline: "#9a9078",
        "surface-container-highest": "#2a3548",
        "primary-fixed-dim": "#f1c100",
        "secondary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary": "#67001b",
        "on-tertiary-fixed": "#40000d",
        "outline-variant": "#4e4632",
        "tertiary-container": "#ffc3c6",
        "on-background": "#d8e3fb",
        "secondary-container": "#00a6e0",
        "on-primary": "#3d2f00",
        "on-secondary-fixed": "#001e2c",
        "on-primary-fixed": "#241a00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        sm: "8px",
        base: "4px",
        xs: "4px",
        md: "16px",
        lg: "24px",
        gutter: "16px",
        "container-margin": "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
